// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_AGN94O41y7DxugoWZMH-lTokU9DDNhA',
    appId: '1:191310674371:android:45aa3a4fa70d3af086a576',
    messagingSenderId: '191310674371',
    projectId: 'allthewayhome-b3ee9',
    databaseURL: 'https://allthewayhome-b3ee9-default-rtdb.firebaseio.com',
    storageBucket: 'allthewayhome-b3ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1vJAxpQLJSrNzjGWmyHUo5eeFbulLvA',
    appId: '1:191310674371:ios:2aeffc4e322bb2f186a576',
    messagingSenderId: '191310674371',
    projectId: 'allthewayhome-b3ee9',
    databaseURL: 'https://allthewayhome-b3ee9-default-rtdb.firebaseio.com',
    storageBucket: 'allthewayhome-b3ee9.appspot.com',
    iosClientId: '191310674371-slc2dbvf9pn3prd2vcisnfem7s03caqf.apps.googleusercontent.com',
    iosBundleId: 'com.allthewayhome.app',
  );
}
